### ISSUE TITLE
Mod Organizer Fails to Launch game via SKSE

### ISSUE THREAD

**Issue by Justgoosing** [SovnSkyrim/Aldrnari#19]
Version V1.2 | 'till it's over
Specs: RTX 3080, Ryzen 3900X, Aldrnari downloaded on SSD under own folder in C Drive not Program Files, downloads on HDD

This is an awesome mod list and appreciate all the work that went into this, previous versions have worked so I am not sure why the game is not launching via Mod Organizer through SKSE.  Mod Organizer seems to be timing out.  Have redownloaded and followed the instructions verbatim.  Any known issues or options to get around this? 

Mod Log: [2021-10-30 06:49:11.912 D] timing: MainWindow::checkForProblemsImpl() 148 ms

Thanks again for this dope ass list, been itching to get back in ;)

**Comment by SovnSkyrim** [comment]
not the place, go in discord.
