### ISSUE TITLE
"Hashed download is incorrect" issue.

### ISSUE THREAD

**Issue by Auriel68** [SovnSkyrim/Aldrnari#20]
Hello,
Trying to install since yesterday with latest wabbajack executable and every time shows "Hashed download is incorrect" for several files, all of them Skyrim core files. Attempted a couple times with Wabbajack 2.5.3.1 and 2.5.2.2 just for the sake of it with same result. Am I missing something? Please see attached wabbajack.current.log
I can't wait to try your modlist.
Keep up with the good work.
[Wabbajack.current.log](https://github.com/SovnSkyrim/Aldrnari/files/7627813/Wabbajack.current.log)
k.

**Comment by SovnSkyrim** [comment]
This isn't the place; use the Discord servers within the readme.
No support will be provided on Git.
