### ISSUE TITLE
Modlist V1.4.2 - Unable to download several files (not listed in readme)

### ISSUE THREAD

**Issue by medinaKrom1** [SovnSkyrim/Aldrnari#23]
Hi and a good new year Sovn,

I have several files unable to download. Tried it 3 times today.
Added the last lines of the wbbajack log file.
So I'm nut sure what the reason is. All other files were downloaded correctly.
Not using the Anniversary version of Skyrim.

Would be glad for a little help for this fantastic modlist.

2323.74 - Unable to download Data_ccBGSSSE025-AdvDSGS.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\ccbgssse025-advdsgs.bsa)
2323.74 - Unable to download Data_ccBGSSSE025-AdvDSGS.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\ccbgssse025-advdsgs.esm)
2323.74 - Unable to download Aldrnari - Lods Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Aldrnari - Lods Output.7z_55bcadb1-7f52-4950-9c87-7e8f9faacb17)
2323.74 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - animations.bsa)
2323.74 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - interface.bsa)
2323.74 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - meshes0.bsa)
2323.74 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - meshes1.bsa)
2323.74 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - misc.bsa)
2323.74 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - shaders.bsa)
2323.74 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - sounds.bsa)
2323.74 - Unable to download Data_Skyrim - Textures1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures1.bsa)
2323.74 - Unable to download Data_Skyrim - Textures2.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures2.bsa)
2323.74 - Unable to download Data_Skyrim - Textures4.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures4.bsa)
2323.74 - Unable to download Data_Skyrim - Textures5.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures5.bsa)
2323.74 - Unable to download Data_Skyrim - Textures6.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures6.bsa)
2323.74 - Unable to download Data_Skyrim - Textures7.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures7.bsa)
2323.74 - Unable to download Data_Skyrim - Textures8.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.342.0|data\skyrim - textures8.bsa)
2323.74 - Cannot continue, was unable to download one or more archives
2323.74 - File hash check (-42) b0d5dde21b778a964e8528c1a32014ebf3e3f3e83df667a708eeb474fe3ad52c
2323.74 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
2324.15 - File hash check (-42) b0d5dde21b778a964e8528c1a32014ebf3e3f3e83df667a708eeb474fe3ad52c

**Comment by medinaKrom1** [comment]
After updating to Anniversary Update und verifying local files of Skyrim installation via steam client, the installation is continuing now with the step "Extracting modlist".

Maybe you can update the readme for a notice that the Anniversary update is necessary.
Thanks.

**Comment by SovnSkyrim** [comment]
If only you'd read the documentation properly.
