### ISSUE TITLE
default screenshot directory path needs attention

### ISSUE THREAD

**Issue by Ekynox** [SovnSkyrim/Aldrnari#25]
Hi Devs, Sovn, 

I noticed that when taking a screenshot in-game ("Print Screen" key), it tries and fails to file it under `C:/Games/Screenshots/Tinvaak/WIP`.

That can be corrected in the SkyrimCustom.ini file:
```
[Display]
sScreenShotBaseName=C:/Games/Screenshots/Tinvaak/WIP
```

This Skyrim bundle is an incredible amount of work! Thumb-up Sovn !!!

**Comment by SovnSkyrim** [comment]
read the readme
