### ISSUE TITLE
Daedroth and Dread Daedroth from Mihails mod aren't considered summons by conjuration tree perks

### ISSUE THREAD

**Issue by cozycaco** [SovnSkyrim/Aldrnari#26]
Hey Sov, its Cozy, loving your stuff, but found a bug I'd like to bring to your attention. After testing, both with Edge of Oblivion, the perk that causes a debuff when you have no spawned in summons or reanimated, and Planemeld, which extends cast range on non undead summons, both of which do not recognize the conjure daedroth, or conjure dread daedroth spells as being applicable, as well with the creatures they spawn, it appears that the creatures and spells are not being picked up by the ordinator perks for some reason or another. I have had 2 spawned in daedroth and still get the edge of oblivion debuff, which immediately went away when I spawned a different creature, and their conjuration spell still has the default range even with planemeld, which effects other spells and mihail mods just fine. Extremely minor, but I like to document these things as I find a good amount of info and can replicate them personally.

**Comment by SovnSkyrim** [comment]
Use the discord; not git.
