### ISSUE TITLE
Aldrnari 2.1 - Bow Rapid Combo not fully working

### ISSUE THREAD

**Issue by Kathaarian** [SovnSkyrim/Aldrnari#31]
_Issue:_
As is, only the basic 'rapid shot' function is working when using a bow and pressing M2, trying all the other shot types with directional key requirements (such as multi-shot with forward+M2) only does another rapid shot.

_Suggested partial fix:_
[dTry's Key Utils](https://www.nexusmods.com/skyrimspecialedition/mods/69944) is listed as a requirement for the mod and after installing it, I managed to get everything but the triple shot and the multi shot working properly - both of those make the player character T-pose instead with no arrows fired. As the Bow Rapid Combo description mentions, these two are the only 'combo' moves, so there is something wrong with the input when you chain the same shot twice. 
In the Bugs tab someone else was having the same issue and they claimed to have fixed it by installing MCO, no idea if that helps since animation issues are beyond me to troubleshoot.

**Comment by SovnSkyrim** [comment]
This isnt the place to make bug reports.

**Comment by Ameno-Sagiri** [comment]
Why? Every other project collaborator/organizer/developer uses this for bug reports. This is a bug reporting section. I'm not using discord. Act like a proper developer.

**Comment by SovnSkyrim** [comment]
This isn't a developper project; i'm not submitting code, I'm taking notes elsewhere on bug reports; I answer ASAP on Discord when issues arise. 
I dont care what your beliefs are, I've been doing lists for longer than I was a developper; I've always functionned that way.
It also allows me to ban assholes that dont follow rules.
If you'd use Discord, "lo and behold", you'd know why it doesnt work.

This isn't a bug, you're just unable to read.
