### ISSUE TITLE
Weapon & arrow dont appear

### ISSUE THREAD

**Issue by MeriusTz** [SovnSkyrim/Aldrnari#33]
Hi !
I don't like the 3rd person in combat, and if I disable it "Seamless Combat Camera" on MO, weapons and arrow are no longer modeled in first person if i do it.

**Comment by SovnSkyrim** [comment]
You have not read the readme.

**Comment by MeriusTz** [comment]
Is there a way to disable the 3rd person forced without getting invisible weapon ?

**Comment by MeriusTz** [comment]
i dont see any mention of this bug on the readme

**Comment by SovnSkyrim** [comment]
This is the repository for the readme; talking here is extremely slow and to have efficient support we use Discord. Please use Discord for question.
As for third person.
In the FAQ:
`I keep getting put into 3rd/third person when in combat

Intended; the list is tailored to 3rd person combat. More information in the [Modified Gameplay.md](https://github.com/SovnSkyrim/Aldrnari/blob/main/Modified%20Gameplay.md).`
Which describes 
`[Seamless Combat Camera](https://www.nexusmods.com/skyrimspecialedition/mods/53856) will force you in 3rd person for every fight. You will only be able to fight in third person, and that's intended. There are no first person combat mods in the list which means that; if disabled; you have vanilla combat against enemies with way more mechanics and tools.`

Id suggest playing another list if you wish to use first person.
