### ISSUE TITLE
Interrupting Magic

### ISSUE THREAD

**Issue by Tuundrraa** [SovnSkyrim/Aldrnari#34]
So, when casting continuous spells like Healing, Flame, ect, it gets automatically interrupted sometimes, hold down button, it'll trigger for a second then just stop. 

Same with Conjuration, I'll start to charge the spell, and sometimes it'll just eat the mana but not cast anything, or even cut the charge short, and eat the mana. 

Help 🙃 thank you

**Comment by Tuundrraa** [comment]
I'm just dumb, it's a mod

**Comment by SovnSkyrim** [comment]
Please read the readme to report issues (aka not here)
