### ISSUE TITLE
Missing Download

### ISSUE THREAD

**Issue by steveyminecraft** [SovnSkyrim/Aldrnari#35]
Hi there I am trtying to install Aldnari for the frist time however I keep getting this error

`Unable to download Serenity 3DNPC BSA Proper.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Serenity 3DNPC BSA Proper.7z_fdc6bf82-2a9c-4ed1-bd1d-1408cb02ef49/)`

Seem this file isn't resolved at all and is causing the downloader to fail, this file is on the nexus so perhaps update the location?

**Comment by SovnSkyrim** [comment]
pls read the readme.
