### ISSUE TITLE
SO i've followed the instructions of the entire readme and everything for aldrnari download and installation

### ISSUE THREAD

**Issue by SoulSaki6** [SovnSkyrim/Aldrnari#38]
And when i launch skse through mod organizer my skyrim doesn't load up at all and it was downloaded on a clean install and everything

**Comment by SovnSkyrim** [comment]
still not the place to ask questions. This is the repository for the readme. Use the discord or else you're gonna keep waiting between 5 to 10h for answers where you could get one in discord much faster.
