### ISSUE TITLE
Blank "ok" boxes 

### ISSUE THREAD

**Issue by xsquigsx** [SovnSkyrim/Aldrnari#42]
[](url)
![sky1](https://github.com/SovnSkyrim/Aldrnari/assets/138566970/9df162f7-2885-44ee-b2a2-ee00dce68c97)
![sky2](https://github.com/SovnSkyrim/Aldrnari/assets/138566970/f63bb362-e074-49d3-827d-c032eff67d37)

how to fix these blank boxes, haven't downloaded any other mods or changed any mod orders

**Comment by SovnSkyrim** [comment]
Not the right place for issues; the readme tells you where to report such things.

**Comment by xsquigsx** [comment]
if you mean the discord ive already done that and noone could help sadly

**Comment by SovnSkyrim** [comment]
the probability you'll get helped here is infinitely lower.
