### ISSUE TITLE
Tournament of the Ten Bloods - She Who Erases - Mountains hiding passage entrance near Kagrenzel, and burring statue. 

### ISSUE THREAD

**Issue by LeFrenchyCG** [SovnSkyrim/Aldrnari#43]
Without Cathedral - Improved Mountain LOD and Z Fight Patch (WIP) -->
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/4ae3454a-6d25-4032-acb6-432b35c262b1)
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/614078bf-11dd-46cf-a085-f51a5ff52762)
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/4b73a872-fdd6-4586-9854-88c7f0c755cb)

With Cathedral - Improved Mountain LOD and Z Fight Patch (WIP) -->
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/93b465ed-0caa-415d-927b-59ded2d28054)
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/0cba4e92-bec9-49db-b7ff-c37ad2563d7d)
![image](https://github.com/SovnSkyrim/Aldrnari/assets/143665619/1beaa2e0-fe48-4195-8fc9-c2b3db5b14d6)

If I try to remove Cathedral - Improved Mountain LOD and Z Fight Patch (WIP), it completely breaks the game map

Can we get a patch please? :) 

Thank you in advance.

**Comment by SovnSkyrim** [comment]
Not the place to post bug reports; please read the readme on how
