### ISSUE TITLE
The picture with keybinds is no longer available

### ISSUE THREAD

**Issue by jwlp93** [SovnSkyrim/Aldrnari#45]
Hello

Would be helpful if what the title reffers to was updated. Since I now only know of the keys listed in the readme, which it seems to suggest to not be close to all of them. And considering there are conflicts in the binds that are mentioned, I'd like to see if there are more among the new keybinds I do not know of.

Well I think I've made my point

Thanks for setting all of this up. I've tried doing it myself with 1k mods or so, even that gave me to much of a headache to complete.

**Comment by SovnSkyrim** [comment]
keybinding picture back up.
If you have issues, use the Discord, not the issues tab in Github.
